### ISSUE TITLE
A small change to the snippet of "Insert code" for more convenience

### ISSUE THREAD

**Issue by lostpg** [robole/vscode-markdown-shortcuts#3]
Many thanks for your contributions to this extension!

Most time, when I insert some code in Markdown, I want to specify the language of code. The current snippet of "insert code" will generate two lines of code fence, with a new line in between, with the cursor at new line. 
So I:

1. press a <kbd>backspace</kbd> first and get back to the upper code block fence.
2. Type the code language.
3. Press an <kbd>Enter</kbd>.

And finally start to code. 

The operations are not much complex, but I think they can be simpler.

````
Currently:
```
_  <- cursor here at the new line
```

New:
```_  <- cursor here, so I can just type the language name then press enter and start coding
```
````

With the new snippet, I just type the language name, then <kbd>Enter</kbd> to the new line. It should be more practical.

**Comment by robole** [comment]
Hello @lostpg 

This extension does not contain the snippet you mention. It is only shortcuts for snippets in this extension.

The "insert code" snippet is inside VS Code (builtin). You would need to [raise the issue on the vscode repo](https://github.com/microsoft/vscode/issues) if you think it should be changed. 

I would suggest that you change the snippet yourself instead. Add your own version to your user snippets for markdown. You might need to disable the builtin snippet if you use the same prefix, I dont know as I have not done this myself. You can do this  by calling the command "insert snippet" and search for the snippet "insert code", then click on the eye (as per photo below).

![hide insert code](https://user-images.githubusercontent.com/3703647/128862501-a7afc4e4-a0c8-42dc-adf6-3f9aafff6a9c.png)

Since there is no action for me to take, I will close the issue.

All the best
